__name__ = "clsmview"
__author__ = "Thomas-Otavio Peulen"
__version__ = "0.0.1"
__copyright__ = "Copyright (C) 2021 Thomas-Otavio Peulen"
__credits__ = ["Thomas-Otavio Peulen"]
__maintainer__ = "Thomas-Otavio Peulen"
__email__ = "thomas@peulen.xyz"
__url__ = "https://gitlab.peulen.xyz/tpeulen/clsmview"
__license__ = 'GPL2.1'
__status__ = "Dev"
__description__ = """CLSMview: is a tool to create CLSM images and select photons for a detailed downstream analysis."""
__app_id__ = "F25DCFFA-1234-4643-BC4F-2C3A20495917"
LONG_DESCRIPTION = """CLSMview: a tool to create CLSM images and select photons in CLSM image streams."""
help_url = 'https://gitlab.peulen.xyz/tpeulen/clsmview'
update_url = 'https://gitlab.peulen.xyz/tpeulen/clsmview'
