stages:
  - build
  - test
  - deploy
  - Trigger-cross-projects

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build:linux:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  script:
    - source activate
    - cp .condarc ~/.condarc
    - conda install mamba=$MAMBA_VERSION boa conda-verify
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

test:linux:
  stage: test
  tags:
    - linux
  image: ubuntu:18.04
  before_script:
    # Issue with OpenGL and X11 display
    # See: https://stackoverflow.com/questions/65675765/is-it-possible-to-run-x11-on-gitlab-ci
    # See: https://github.com/conda-forge/pygridgen-feedstock/issues/10
    # procps is used to grep the process by name to kill it when needed
    - |
      apt update -y
      apt install -y xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libgl1-mesa-glx procps wget
      wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p /miniconda3
      export PATH="/miniconda3/bin:$PATH"
      conda config --set always_yes yes --set changeps1 no
      conda init
  script:
    - source activate base
    - cp .condarc ~/.condarc
    - conda install mamba=$MAMBA_VERSION
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba install python clsmview
    # fix see: https://stackoverflow.com/questions/62213783/ffmpeg-error-while-loading-shared-libraries-libopenh264-so-5
    - ln -s /miniconda3/lib/libopenh264.so /miniconda3/lib/libopenh264.so.5
    # Run GUI with xvfb
    - |
      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- clsmview &
      sleep 10
      pgrep -f clsmview | awk '{print "kill -9 " $1}' | sh

deploy:linux:
  stage: deploy
  image: continuumio/miniconda3:latest
  tags:
    - linux
  dependencies:
    - build:linux
  script:
    - source activate
    - conda install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_LABEL=$LABEL_RELEASE; else DEPLOY_LABEL=$LABEL_TESTING; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_LABEL} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2

chisurf:
  stage: Trigger-cross-projects
  trigger: chisurf/chisurf
