{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}


package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
#  path: ..
  git_url: ..

build:
  number: 0
  string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  host:
    - python {{ python }}
    - numpy
    - typing_extensions
    - pyyaml
    - setuptools
  build:
    - python {{ python }}
    - numpy
    - setuptools
    - typing_extensions
    - pyyaml
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt
  run:
    - python {{ python }}
    - typing_extensions
    - numpy
    - pandas
    - pyyaml >=5.0.0
    - qtpy
    - pyqt
    - pyqtgraph
    - tttrlib
    - matplotlib
    - opencv
    - openh264 # make sure that libopenh264.so is installed
    - scikit-fluorescence
    - pathlib2 # [py < 3]

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: CLSMviewer application
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
